### ISSUE TITLE
Says to run as root when I am root

### ISSUE THREAD

**Issue by greyhound-forty** [mpscholten/maphosts#1]
When I run the maphosts command it complains that it is unable to write to /etc/hosts and to try again as root. Odd thing is that it does write to /etc/hosts and I am root.

OS=Ubuntu 14.04
ruby --version = ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]

```
➜ root@bebop  ~  maphosts toybox.example.com --to 10.0.0.2
Updating /etc/hosts
Unable to write to /etc/hosts. Trying again as root.

➜ root@bebop  ~  cat /etc/hosts
127.0.0.1       localhost
184.173.216.182 bebop.tech-casts.com    bebop

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
# -----BEGIN SECTION maphosts - /root-----
10.0.0.2 toybox.example.com
# -----END SECTION maphosts - /root-----

➜ root@bebop  ~  whoami                                                                         
root
```

**Comment by mpscholten** [comment]
Hey @greyhound-forty, thanks for reporting this! :)

It seems the `HostManager` is not returning a `Hostsfile` object as expected. Instead it returns a string (https://github.com/mpscholten/maphosts/blob/master/lib/maphosts/host_manager.rb#L39). Now the command [is trying to call `.write` on the string object](https://github.com/mpscholten/maphosts/blob/master/bin/maphosts#L48) instead of the `Hostsfile` object which raises an expection. This exception [is caught](https://github.com/mpscholten/maphosts/blob/master/bin/maphosts#L50) and leads to manual applying the patch via sudo.

Initial the `to_s.strip!` was added in the `HostManager` because I had some weird whitespace issues. But I think these issues are solved now.

I'll let you know when the fix is ready.

**Comment by mpscholten** [comment]
The bug should be fixed with the latest release (see 711ceb441607bd0370d55b33ede5663c9b27d345). You can [get it on rubygems](https://rubygems.org/gems/maphosts) or via `gem update`. I also added some more tests to make sure this won't happen again.

Can you confirm that the fix works?

**Comment by greyhound-forty** [comment]
That did indeed fix it, not sure why I had an older version since I just installed it but good to go now. 

```
➜ root@bebop  ~  maphosts bebop.example.com --to 10.0.0.3
Updating /etc/hosts
```

**Comment by mpscholten** [comment]
Ok that's great. Thanks again and enjoy the rest of your Wednesday :)
